const AllMovies = [
  {
    id: '01',
    genre: ['Crime'],
    title: 'Pulp Fiction',
    releaseDate: new Date(1994, 5, 25),
    imageName: 'pulpFiction.png',
  },
  {
    id: '02',
    genre: ['Crime'],
    title: 'Kill Bill',
    releaseDate: new Date(2003, 1, 19),
    imageName: 'killBill.png',
  },
  {
    id: '03',
    genre: ['Superhero'],
    title: 'Avengers',
    releaseDate: new Date(2012, 6, 12),
    imageName: 'avengers.png',
  },
  {
    id: '04',
    genre: ['Drama'],
    title: 'Inception',
    releaseDate: new Date(2010, 2, 4),
    imageName: 'inception.png',
  },
  {
    id: '05',
    genre: ['Drama'],
    title: 'Bohemian Rhapsody',
    releaseDate: new Date(2018, 5, 8),
    imageName: 'bohemianRhapsody.png',
  },
  {
    id: '06',
    genre: ['Crime'],
    title: 'Jackie Brown',
    releaseDate: new Date(1997, 3, 31),
    imageName: 'jackieBrown.png',
  },
  {
    id: '07',
    genre: ['Drama', 'Crime'],
    title: 'Reservoir Dogs',
    releaseDate: new Date(1992, 10, 6),
    imageName: 'reservoirDogs.png',
  },
  {
    id: '08',
    genre: ['Comedy'],
    title: 'Four Rooms',
    releaseDate: new Date(1995, 4, 28),
    imageName: 'fourRooms.png',
  },
  {
    id: '09',
    genre: ['Comedy'],
    title: 'Ace Ventura: When Nature Calls',
    releaseDate: new Date(1995, 12, 12),
    imageName: 'aceVentura.jpg',
  },
  {
    id: '10',
    genre: ['Comedy'],
    title: 'Dumb And Dumber',
    releaseDate: new Date(1994, 4, 14),
    imageName: 'dumbAndDumber.jpg',
  },
  {
    id: '11',
    genre: ['Superhero'],
    title: 'Fantastic Four',
    releaseDate: new Date(2015, 10, 10),
    imageName: 'fantasticFour.jpg',
  },
  {
    id: '12',
    genre: ['Superhero'],
    title: 'The Amazing Spider-Man 2',
    releaseDate: new Date(2014, 1, 10),
    imageName: 'spiderman.jpg',
  },
];

export default AllMovies;
